// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebCrawler.Models;

#nullable disable

namespace WebCrawler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebCrawler.Models.NodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CrawlTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlMain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WebsiteRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteRecordId");

                    b.ToTable("Node", (string)null);
                });

            modelBuilder.Entity("WebCrawler.Models.NodeNeighbourModel", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<int>("NeighbourNodeId")
                        .HasColumnType("integer");

                    b.HasKey("NodeId", "NeighbourNodeId");

                    b.HasIndex("NeighbourNodeId");

                    b.ToTable("NodeNeighbour", (string)null);
                });

            modelBuilder.Entity("WebCrawler.Models.WebsiteRecordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoundaryRegExp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<int>("Hours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WebsiteRecord", (string)null);
                });

            modelBuilder.Entity("WebCrawler.Models.NodeModel", b =>
                {
                    b.HasOne("WebCrawler.Models.WebsiteRecordModel", "WebsiteRecord")
                        .WithMany("Nodes")
                        .HasForeignKey("WebsiteRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteRecord");
                });

            modelBuilder.Entity("WebCrawler.Models.NodeNeighbourModel", b =>
                {
                    b.HasOne("WebCrawler.Models.NodeModel", "NeighbourNode")
                        .WithMany()
                        .HasForeignKey("NeighbourNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebCrawler.Models.NodeModel", "Node")
                        .WithMany("Neighbours")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NeighbourNode");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("WebCrawler.Models.NodeModel", b =>
                {
                    b.Navigation("Neighbours");
                });

            modelBuilder.Entity("WebCrawler.Models.WebsiteRecordModel", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
