version: '3.8'

services:
  web:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_NAME=postgres
      - DATABASE_PASS=admin
      - DATABASE_USER=postgres
      - DATABASE_SERVER=db  
      - DATABASE_PORT=5432
      - NUMBER_THREADS=2
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "10100:8080"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
